### ISSUE TITLE
Create "Grid" class

### ISSUE THREAD

**Issue by GaryLeutheuser** [caitlinrichard/tic-tac-toe#1]
This class covers functionality for maintaining a 3x3 grid with 1 of 2 symbols occupying each cell, such as is used for tic-tac-toe.

Suggested fields:
- private `GridState`: length 9 array
  - A `0` in a cell indicates X, `1` indicates Y

Public Methods:
- `IsOver`
  - Returns `true` if there are 3 in a row of either symbol (X or Y). Returns `false` otherwise.
- `AddX(int cell)`
  - Adds an X (`0`) to the given cell
- `AddY(int cell)`
   - Adds a Y ('1') to the given cell

Cells are indexed as such:
0 | 1 | 2
3 | 4 | 5
6 | 7 | 8

**Comment by caitlinrichard** [comment]
Class finished and passed all unit tests. Sent push request. Pending approval.
